### ISSUE TITLE
use of aggregation netcdf for water depth maps

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedidepth#10]
In some cases a user has an aggregation netcdf available.

Can we adjust the script in such a way that it can calculate a max waterdepth map directly from the aggregation netcdf?
This would greatly reduce the overhead for users AND provide a more accurate result (because otherwise they'd simply calculate waterdepth maps for each time step and then take the max)

**Comment by lexvand** [comment]
@arjanverkerk Could you make an estimate for this request?

**Comment by arjanverkerk** [comment]
Reading of result files happens through threedigrid. Threedigrid reading of aggregate results is not widely used and Richard and I stumbled over this bug: nens/threedigrid#121

**Comment by Jonasvsl** [comment]
if the bug is fixed I would still very much like this feature

**Comment by arjanverkerk** [comment]
Hey @Jonasvsl, I tihink the bug you are referring to has been fixed at some point, because Threedepth already supports aggregate type results (it uses `s1_max` in that case).

**Comment by Jonasvsl** [comment]
does this mean that a user can calculate max water depth for a complete simulation without building all the individual water depth maps by using this tool? 
in other words, can I ask Lutra consulting to built this ui on this tooling?
This would be a very very much requested feature

**Comment by arjanverkerk** [comment]
I see... This issue until now only implements calculating the depth maps _for some a calculation step_ on the aggregate results file instead of the standard (snapshot) results file, but does not calculate an overall maximum waterdepth.

**Comment by arjanverkerk** [comment]
Refer to #19 for the maximum over all calculation steps aggregation.
