### ISSUE TITLE
Add maximum waterdepth output that aggregates all calculation steps

### ISSUE THREAD

**Issue by arjanverkerk** [nens/threedidepth#19]
Add --maximum option, not to be combined with --steps option, that triggers calculation of a maximum waterdepth map.

**Comment by Jonasvsl** [comment]
to be clear: this can be done one the result netcdf or on the aggregation netcdf?

if the max waterdepth can be calculated without having to generate all the geotiffs first this would be a great enhancement and a much needed user requested feature

**Comment by arjanverkerk** [comment]
The input for the script is either the result netcdf or the aggregation netcdf and yes, it would work for both. It will not check if the aggregation is actually a maximum aggregation, i guess, that's the responsibility of the user. And it will take the maximum of the coarse waterlevels, and compute depth only once. At least that is what I had in mind, so let me know if that's ok.

**Comment by leendertvanwolfswinkel** [comment]
Yes, the idea is that we calculate the maximum water level per cell _before_ interpolation

**Comment by leendertvanwolfswinkel** [comment]
@elisallenens Please make spatial interpolation optional, similar to the existing 'water level' and 'water depth' algorithms

**Comment by caspervdw** [comment]
I discussed this with @elisallenens  today, and what is missing here is a detailed technical plan on how to implement this new feature. Eli will need help with this, as this is his first time doing anything with a 3Di result. @arjanverkerk is the logical mentor here. Could you two together make a plan with some bullet points in what needs to be done for the maximum feature?
