### ISSUE TITLE
Investigate bilinear interpolation using s1 at velocity points

### ISSUE THREAD

**Issue by arjanverkerk** [nens/threedidepth#20]
The previous investigation used bilinear on the whole cell, where corners where calculated from contributing neighbouring calculation cells. Big drawback was that the face value of the calculation cell was never arrived at, not even in the middle of the face (as is the case with constant and delaunay methods).

The next idea is therefore to divide a mesh face into four quadrants and use the (upwind) s1 values on velocity points (on the edges), the face value and a computed corner value as the inputs for bilinear interpolation.

```
      V         V  
      │         │  
      │         │  
─V────C────V────C────V─
      │    ·    │  
      │    ·    │  
      V····M····V  
      │    ·    │  
      │    ·    │  
─V────C────V────C────V─
      │         │  
      │         │  
      V         V  

```
The corners for the bilinear interpolation are C, V, V and M:

C is a computed value (we can start with the average of the velocity point values)
V are the (upwind) velocity point values
M is the face value

This is done on each quadrant of a calculation cell. Some additional choices have to be made near refinements, of course.

Edit:
2022-03-02 Added "(upwind)" in two places.

**Comment by RemieJanssen** [comment]
I am making several adjusted versions of Arjan's bilinear interpolation.
They all use bilinear interpolation on the four corner squares of each calculation cell.
This requires calculating the values for the V and C parts of Arjan's diagram above.
Which can be done in several ways:
 - [remie-bilinear_with_corners](https://github.com/nens/threedidepth/tree/remie-bilinear_with_corners)
_Calculates C values as in Arjan's version, and V values as the average of the adjancent C values._
 - [remie-bilin_corners_T_as_mean](https://github.com/nens/threedidepth/tree/remie-bilin_corners_T_as_mean)
_Calculates C values as a mean of the adjacent faces (without the exception for T-intersections as in ARjan's code), and V values as the average of adjacent C nodes._
 - [remie-interpolate_middles_between_faces](https://github.com/nens/threedidepth/tree/remie-interpolate_middles_between_faces)
_Calculates V values as average of the two adjacent faces (calculation cells). At T-intersections and for the V-values for small faces on the 'long side' of T-intersections, these values must be overwritten with averages of adjacent nodes in the end to achieve continuous interpolation. The C-values are simply averages of the adjacent faces._

**Comment by RemieJanssen** [comment]
Still to do: A version that uses the sau values of the result file as the V-values wherever possible.

**Comment by Patrick-Nijman** [comment]
@lexvand Waarom is dit weer naar New Issues gegaan? Ik had eigenlijk gehoopt dat Arjan dit af kon maken. Is het enige open issue in de Epic. Kan dit eventueel gesloten worden of als losse issue verder opgepakt worden?

**Comment by lexvand** [comment]
Not sure what the status of this project is. Closing this issue as it seems like it has been investigated. Any leftover work should be put in a new issue.
