### ISSUE TITLE
how is output resolution calculated?

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedidepth#9]
is it a parameter in the script or is it always 0.5 m2?

@RichardB9 @arjanverkerk

**Comment by RichardB9** [comment]
It's not a parameter, you can find the parameters of the script and their descriptions here: https://github.com/nens/threedidepth/blob/ac4755735fd8f53730a9ccae3a37e2ac56bf8d57/src/threedidepth/calculate.py#L431

**Comment by Jonasvsl** [comment]
my apologies, it appears the dem file is 0.5 x 0.5 after all, it just has a weird name as '5m'
